// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLB4ukUs2_WZZ8dBdTHraeyFRI1DtOA1A',
    appId: '1:470278129082:web:386f314595093c49828983',
    messagingSenderId: '470278129082',
    projectId: 'emra-d0269',
    authDomain: 'emra-d0269.firebaseapp.com',
    storageBucket: 'emra-d0269.appspot.com',
    measurementId: 'G-PP9HWWJMBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-tJ7hlHn1priRALZVPkjm0tqDrq0S6g',
    appId: '1:470278129082:android:0f70d0a0ac400d41828983',
    messagingSenderId: '470278129082',
    projectId: 'emra-d0269',
    storageBucket: 'emra-d0269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEkPwIfprIrYs7bnAOCjHhtdiREssYPg',
    appId: '1:470278129082:ios:175da686d5d1fa97828983',
    messagingSenderId: '470278129082',
    projectId: 'emra-d0269',
    storageBucket: 'emra-d0269.appspot.com',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEkPwIfprIrYs7bnAOCjHhtdiREssYPg',
    appId: '1:470278129082:ios:2dcc8ef7c4145b60828983',
    messagingSenderId: '470278129082',
    projectId: 'emra-d0269',
    storageBucket: 'emra-d0269.appspot.com',
    iosBundleId: 'com.example.emergencyApp.RunnerTests',
  );
}
